version: "3.8"

services:
  elasticsearch_master:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: elasticsearch_master
    environment:
      - node.name=elasticsearch_master
      - XXX_cluster.name=docker-cluster
      - discovery.type=single-node
      - XXX_cluster.initial_master_nodes=elasticsearch_master
      - XXX_node.master=true
      - bootstrap.memory_lock=true
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - ES_JAVA_OPTS=-Xms4G -Xmx4G
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - xpack.security.enabled=$ELASTIC_SECURITY
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - data01:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
volumes:
  data01:
    driver: local